jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthenticationFilter
        - id: servico-eventos
          uri: lb://servico-eventos
          predicates:
            - Path=/api/events/**
          filters:
            - JwtAuthenticationFilter
        - id: servico-pedidos
          uri: lb://servico-pedidos
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthenticationFilter
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtAuthenticationFilter
        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtAuthenticationFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/